services:
  admin:
    build:
      context: .
      dockerfile: adminClient/Dockerfile
    ports:
      - "19001:19001"
    volumes:
      - ./adminClient:/app
    command: npx expo start --port 19001

  professional:
    build:
      context: .
      dockerfile: professionalClient/Dockerfile
    ports:
      - "19002:19002"
    volumes:
      - ./professionalClient:/app
    command: npx expo start --port 19002

  client:
    build:
      context: .
      dockerfile: fixerClient/Dockerfile
    ports:
      - "19003:19003"
    volumes:
      - ./fixerClient:/app
    command: npx expo start --port 19003
