services:
  admin:
    build:
      context: .
      dockerfile: adminClient/Dockerfile
    ports:
      - "19001:19000"
    volumes:
      - ./adminClient:/app
    command: npx expo start --port 19000

  professional:
    build:
      context: .
      dockerfile: professionalClient/Dockerfile
    ports:
      - "19002:19000"
    volumes:
      - ./professionalClient:/app
    command: npx expo start --port 19000

  client:
    build:
      context: .
      dockerfile: fixerClient/Dockerfile
    ports:
      - "19003:19000"
    volumes:
      - ./fixerClient:/app
    command: npx expo start --port 19000
