name: individual-coverage-report
on:
  pull_request_target:
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [professionalClient, fixerClient]
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
        working-directory: professionalClient
      - name: List installed packages
        run: npm list
        working-directory: professionalClient
      - name: Jest Annotations & Coverage
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: ${{ matrix.directory }}
