name: suite-folded-ctrf

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  testing-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }} # Use the current branch

      - name: Install Dependencies
        run: npm install
        working-directory: fixerClient

      - name: List Installed Packages
        run: npm list
        working-directory: fixerClient

      - name: Run Jest Tests
        run: npx jest || true
        working-directory: fixerClient

      - name: Publish CTRF Suite Folded Summary
        run: npx github-actions-ctrf suite-folded fixerClient/ctrf/ctrf-report.json
        if: always()

      - name: Publish CTRF Pull Request Comment
        run: npx github-actions-ctrf pull-request fixerClient/ctrf/ctrf-report.json
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
