name: suite-folded-ctrf

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  testing-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run CTRF annotations
        run: npx github-actions-ctrf summary professionalClient/ctrf/ctrf-report.json
        if: always()
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
        with:
          working-directory: professionalClient 
      - name: Publish CTRF Suite Folded Summary
        run: npx github-actions-ctrf suite-folded path-to-your-ctrf-report.json
        if: always()
      - name: Publish CTRF pull request comment
        run: npx github-actions-ctrf pull-request professionalClient/ctrf/ctrf-report.json
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
