name: suite-folded-ctrf

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  testing-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
        working-directory: professionalClient
      - name: List Installed Packages
        run: npm list
        working-directory: professionalClient
      - name: npx jest
        run: npx jest professionalClient || true
        working-directory: professionalClient
      - name: Publish CTRF pull request comment
        run: npx github-actions-ctrf pull-request professionalClient/ctrf/ctrf-report.json || true
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}