name: global-coverage

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened] # Optional: specify events to trigger

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        working-directory: professionalClient

      - name: List Installed Packages
        run: npm list
        working-directory: professionalClient

      - name: npx jest
        run: npx jest || true
        working-directory: professionalClient
        continue-on-error: true

      - name: Jest Annotations & Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: professionalClient
          continue-on-error: true
