name: PR analysis
on:
  pull_request:
    types: [opened, reopened]
jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Run tests on pull request
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm install
        working-directory: professionalClient

      - name: Run Jest PR analysis
        run: |
          cd professionalClient
          npx jest --ci --reporters=default --reporters=jest-pr-report --reporters=jest-junit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
