name: coverage-report
on:
  pull_request_target:
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [professionalClient, fixerClient]  # Add both client directories here
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
        working-directory: ${{ matrix.dir }}  # Use the matrix variable
      - name: List installed packages
        run: npm list
        working-directory: ${{ matrix.dir }}  # Use the matrix variable
      - name: Jest Annotations & Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: ${{ matrix.dir }}  # Use the matrix variable
