name: PR analysis
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Run tests on pull request
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm install
        working-directory: professionalClient

      - name: Jest PR analysis
        uses: Manogel/jest-pr-analysis@v1.1.1

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}